# Generated by Django 3.2.5 on 2022-07-16 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0003_auto_20220717_0341'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='dummy',
            field=models.CharField(default='dummy', max_length=2),
            preserve_default=False,
        ),
    ]
