# Generated by Django 3.2.5 on 2022-07-16 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0004_location_dummy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetups',
            name='location',
        ),
    ]
