# Generated by Django 3.2.5 on 2022-07-16 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0008_meetups_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetups',
            name='location',
        ),
    ]
